### ISSUE TITLE
Feature: status indicator for resolved help requests

### ISSUE THREAD

**Issue by jagaSto** [kenodressel/quarantine-hero#107] opened 2020-03-21 21:45 UTC
Just brainstorming here, what do you guys think of a status indicator for help requests?

Currently, it is pretty transparent of no one has offered any help yet for a request (`Noch keine Nachrichten erhalten`) and if somebody already offered some help (`\d Nachrichten erhalten`).
However, especially for older requests (> X days), I don't think that it's very transparent if the request still needs support. This probably leads to a lot of unnecessary additional help offerings (`Hey, brauchst du noch Hilfe?`), and many unnecessary replies (`Danke, aber mir wurde schon geholfen!`). 

To mitigate this, we could ask the creator of the help request whether help is still desired.
We could either ask the user to mark the issue as resolved or delete it completely.
 I don't know what benefits we would have from still showing a resolved request, other than that users are still able to engage with the help seeker and that it shows that we have a lot of traffic.

For this, we could periodically ask creators of help requests older than X days if the request is still open, or if it can be closed/tagged as solved.

What do you guys think? I saw some code snippets in the `Entry.jsx` for a delete handling, but so far it only seems to be available for a very specific [user id](https://github.com/kenodressel/quarantine-hero/blob/a278f32bb91157c8c477ea91c7316296337db92e/src/components/Entry.jsx#L121-L122) ;)

**Comment by timjb** [comment] 2020-03-21 23:26
> For this, we could periodically ask creators of help requests older than X days if the request is still open, or if it can be closed/tagged as solved.

Additionally/alternatively we could ask the creator of a help request in each email for every offer they receive to mark the request as resolved if they do not wish to receive further offers.

**Comment by Maurice22** [comment] 2020-03-22 13:42
Duplicate of #21

**Comment by tgraupne** [comment] 2020-03-22 19:55
Closed due to duplication.

**Closed by tgraupne** 2020-03-22 19:55 UTC
Labels: enhancement
