### ISSUE TITLE
Dashboard error "Missing or insufficient permissions"

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#48] opened 2020-03-19 11:58 UTC
Dashboard throws error "Missing or insufficient permissions" and notification registrations not deletable.

**Comment by kenodressel** [comment] 2020-03-20 09:43
This seems like an even bigger problem in firefox because there the `&times` icon is not even clickable

**Comment by Maurice22** [comment] 2020-03-20 10:18
Same in Chrome

**Comment by timjb** [comment] 2020-03-20 15:08
This might be caused by the dashboard code using '0' as a fallback for loading requests for help and notifications. If that is the cause, then this issue will be fixed by my PR https://github.com/kenodressel/quarantine-hero/pull/78.

**Comment by Maurice22** [comment] 2020-03-20 15:10
@kenodressel ?

**Comment by kenodressel** [comment] 2020-03-20 16:12
Well should be fixed then, can anyone confirm?

**Comment by Maurice22** [comment] 2020-03-20 16:17
Confirming no "Insufficient permission" error anymore

**Closed** 2020-03-20 16:26 UTC
Labels: bug
